export const countries = [
  { value: 'AD', label: 'Andorra'	},
  { value: 'AR', label: 'Argentina'	},
  { value: 'AS', label: 'American Samoa'	},
  { value: 'AT', label: 'Austria'	},
  { value: 'AU', label: 'Australia'	},
  { value: 'BD', label: 'Bangladesh'	},
  { value: 'BE', label: 'Belgium'	},
  { value: 'BG', label: 'Bulgaria'	},
  { value: 'BR', label: 'Brazil'	},
  { value: 'CA', label: 'Canada'	},
  { value: 'CH', label: 'Switzerland'	},
  { value: 'CZ', label: 'Czech Republic'	},
  { value: 'DE', label: 'Germany'	},
  { value: 'DK', label: 'Denmark'	},
  { value: 'DO', label: 'Dominican Republic'	},
  { value: 'ES', label: 'Spain'	},
  { value: 'FI', label: 'Finland'	},
  { value: 'FO', label: 'Faroe Islands'	},
  { value: 'FR', label: 'France'	},
  { value: 'GB', label: 'Great Britain'	},
  { value: 'GF', label: 'French Guyana'	},
  { value: 'GG', label: 'Guernsey'	},
  { value: 'GL', label: 'Greenland'	},
  { value: 'GP', label: 'Guadeloupe'	},
  { value: 'GT', label: 'Guatemala'	},
  { value: 'GU', label: 'Guam'	},
  { value: 'GY', label: 'Guyana'	},
  { value: 'HR', label: 'Croatia'	},
  { value: 'HU', label: 'Hungary'	},
  { value: 'IM', label: 'Isle of Man'	},
  { value: 'IN', label: 'India'	},
  { value: 'IS', label: 'Iceland'	},
  { value: 'IT', label: 'Italy'	},
  { value: 'JE', label: 'Jersey'	},
  { value: 'JP', label: 'Japan'	},
  { value: 'LI', label: 'Liechtenstein'	},
  { value: 'LK', label: 'Sri Lanka'	},
  { value: 'LT', label: 'Lithuania'	},
  { value: 'LU', label: 'Luxembourg'	},
  { value: 'MC', label: 'Monaco'	},
  { value: 'MD', label: 'Moldavia'	},
  { value: 'MH', label: 'Marshall Islands'	},
  { value: 'MK', label: 'Macedonia'	},
  { value: 'MP', label: 'Northern Mariana Islands'	},
  { value: 'MQ', label: 'Martinique'	},
  { value: 'MX', label: 'Mexico'	},
  { value: 'MY', label: 'Malaysia'	},
  { value: 'NL', label: 'Holland'	},
  { value: 'NO', label: 'Norway'	},
  { value: 'NZ', label: 'New Zealand'	},
  { value: 'PH', label: 'Phillippines'	},
  { value: 'PK', label: 'Pakistan'	},
  { value: 'PL', label: 'Poland'	},
  { value: 'PM', label: 'Saint Pierre and Miquelon'	},
  { value: 'PR', label: 'Puerto Rico'	},
  { value: 'PT', label: 'Portugal'	},
  { value: 'RE', label: 'French Reunion'	},
  { value: 'RU', label: 'Russia'	},
  { value: 'SE', label: 'Sweden'	},
  { value: 'SI', label: 'Slovenia'	},
  { value: 'SJ', label: 'Svalbard & Jan Mayen Islands'	},
  { value: 'SK', label: 'Slovak Republic'	},
  { value: 'SM', label: 'San Marino'	},
  { value: 'TH', label: 'Thailand'	},
  { value: 'TR', label: 'Turkey'	},
  { value: 'US', label: 'United States'	},
  { value: 'VA', label: 'Vatican'	},
  { value: 'VI', label: 'Virgin Islands'	},
  { value: 'YT', label: 'Mayotte'	},
  { value: 'ZA', label: 'South Africa'	},
];
